### ISSUE TITLE
Translations folder missing

### ISSUE THREAD

**Issue by wbinek** [Ifsttar/I-Simpa#113]
I wrote a polish translation to my version of I-SIMPA. After merging with latest version I noticed that locale folder is missing. Are the translations moved somewhere else?

**Comment by nicolas-f** [comment]
Nice. We use Transifex for translation of I-Simpa:
https://www.transifex.com/LAE/i-simpa/dashboard/

It is integrated into the build system.  A transifex client is used to update the .po files for each language in the source tree.

The configuration of language is here:
https://github.com/Ifsttar/I-Simpa/blob/master/src/isimpa/lang/fr/CMakeLists.txt

CMake is calling gettext in order to convert the .po to .mo and then the final .mo files are copied into the install folder https://github.com/Ifsttar/I-Simpa/blob/master/src/isimpa/CMakeLists.txt#L420

**Comment by d-cooper** [comment]
Hi! Thanks for the answer. I added the translation to my fork ( https://github.com/d-cooper/I-Simpa/commit/00ccb26a1976f725f269909554b1f15d80995165 ). If you accept my request on transifex I can upload the translation there as well.
