### ISSUE TITLE
tetgen and sppsNantes issue

### ISSUE THREAD

**Issue by pbasilio** [Ifsttar/I-Simpa#14]
Hello, I've been having issues with I-Simpa, particularly with tetgen.exe and sppsNantes.exe.

I have a .3ds file made in sketchup (I've tried also 3D studio and the same issue applies) and most of the time, if I import the scene with the repair model and try to run the SPPS calculation, either of these apps will crash (usually tetgen.exe), and if i import them with the average model remesh, the spps calculation will only get done if the design is simple, if the design is slightly complex, it will crash.

Also, if the imported scene is slightly complex, the average model remesh will not work properly, it will get some parts of the scene missing.

-Which software offers the best compatibility with I-Simpa? and which format?
-Will I-Simpa be more compatible with windows XP/Vista/7(32bits)?
-Are there any tips regarding the design of the scene? (lines across squared surfaces to create corners, always begin the design in xyz=0, etc.) 

thanks :dancers:

**Comment by d-cooper** [comment]
Hi!

I am not an I-SIMPA developer but I've made many projects using I-SIMPA. 

From my experience the easiest way to make a geometry is to use sketchup. If tetgen crashes or doesn't calculate the mesh it means that there still are some errors in the geometry. I-SIMPA doesn't work well with any intersections or overlapping surfaces. I've also had some problems with to complicated surfaces - sometimes just drawing a line across a surface to split it into smaller parts helps. 

You can try to make mesh using debug option - it will list the errors than you can export the geometry to .poly open it in notepad and check where are the problems. At least that's how I go around it.

Also mind that there is a bug in diffusion calculation (https://github.com/Ifsttar/I-Simpa/issues/5) which I don't know why isn't fixed yet so don't be amazed if you will get awkward results when using diffusion.

Regards

**Comment by pbasilio** [comment]
Thanks! that was really helpful, this time i tried to avoid as much as i could the intersections and overlapping surfaces, and it did the calculations without issues, but when i select the "view>faces>inside" some of the visible surfaces are not quite... visible all the time, maybe I need to keep adding lines across surfaces until they make sense haha!  

The thing that i didn't get is how to use the debug option, I'm sorry if this is too simple... but i don't see any option for that. 

Also, is there a way to hide specific surfaces? 

Thanks again! :cactus:

**Comment by d-cooper** [comment]
The problem with surfaces means that they are not consistently oriented. The program by default hides back of the surface so that you can see the inside of your geometry. When you right-click the surface or surface group in project panel you can select invert normal. You can also invert faces in sketchup.

To make mesh in debug mode you must enter calculations tab->meshing->test mesh topology. When this is selected, tetgen won't output a mesh so you won't be able to make calculations until you deselect the box. When it's selected you can make mesh using icon with square and two lines crossing in its center. In the command window you will see errors found in your geometry. To export geometry to .poly (this is the format that is provided to tetgen, so numbers of nodes and planes in command window are consistent with .poly file) you simply select file->export scene/geometry.

You can try hiding specific surfaces by flipping their normal, but usually when they are properly oriented there is no need for hiding them.

Regards

**Comment by pbasilio** [comment]
Yep, it worked, thanks!

If it isn't too much trouble, how can i correct the diffusion problem?


regards!

**Comment by d-cooper** [comment]
You can download sppsnantes.exe from currentRelease/core/sppscore folder from my fork of I-SIMPA (https://github.com/d-cooper/I-Simpa). It should work fine, although there are some other mostly experimental modifications. If you have any problems, let me know, I can build sppsnantes.exe with only bugfixes.

**Comment by pbasilio** [comment]
Hello again d-cooper, 

I tried the sppsnantes.exe from your account... but I can't make it work, is there any procedure to change the sppsnantes?

thanks!

**Comment by d-cooper** [comment]
Hi!

It should be jest fine to copy my sppsnantes.exe over the original one. If it's not working it means that some of the modifications I've made require my version of I-SIMPA (sorry for inconvenience, I haven't tested my sppsnantes.exe with unmodified I-SIMPA). I can build sppsnantes.exe with just diffusion fixed so it will work with original I-SIMPA and send it to you if you wish.

**Comment by pbasilio** [comment]
If it's not too much trouble, it would be amazing if you can send the diffusion fixed sppsnantes whenever you have free time. 

Thanks! :dancers:

**Comment by d-cooper** [comment]
Ok. I have just one more idea. Please try coping this file to libsimpa folder and see if it works. If not I will make new sppsnantes.exe (however it require the file from this post as well).
[boost_python-vc90-mt-1_57.zip](https://github.com/Ifsttar/I-Simpa/files/71105/boost_python-vc90-mt-1_57.zip)

**Comment by pbasilio** [comment]
No luck... it crashes as well, I only copied the file, I didn't erase the old boost_python file.

:D

**Comment by d-cooper** [comment]
Ok. I've made fixed sppsnantes.exe. It uses newer boost, so it will require the lib from my last post. Everything else is just as in the original file so it should work. Please try and let me know :)
[sppsNantes.zip](https://github.com/Ifsttar/I-Simpa/files/71156/sppsNantes.zip)

**Comment by pbasilio** [comment]
Fantastic! works like a charm, do i need to erase the old boos_python in the libsimpa folder?

Amazing!

btw, I'm practicing in I-simpa a design of a room within a room, and i can't get the animation or the grid to be consistent, it looks like this:

![trying2rooms](https://cloud.githubusercontent.com/assets/16143796/11984130/aaa49c78-a9b0-11e5-908e-494cae629585.png)

I've tried changing the grid resolution but doesn't work, it actually makes it worst.

And... I'm sorry for being too picky, is there a way to save a txt to import the materials including the transmission loss?

the usual would be like CATT acoustics:

UPHOLST_HEAV = <72 79 83 84 83 79> L <30 40 50 60 70 70>
 C:Chairs
 D:Heavily upholstered concert hall chairs, average.
 R:[Beranek]

but, can i include in this txt file transmission loss? 

thanks!

**Comment by d-cooper** [comment]
I am happy it works. You don't have to delete the old file. The .exe I've
send you should work well but to be certain compare the RT results with and
without diffusion.

It looks to me like you have to few particles. Try using more. Are you
using energetic or random approach? From my experience you should always
use energetic - it gives better results (otherwise number of rays decreases
quickly). Moreover I think that especially late part of simulation will
always look kind of random because you will never get ideal diffuse field.

About the transmission loss. As far as I know there is no such way right
now. It can be added, but to be honest there are some modifications I need
waiting and I can't find time to write them so I don't think I will find
time to modify material import any soon - sorry.

Best regards

śr., 23 gru 2015, 21:16 pbasilio użytkownik <notifications@github.com>
napisał:

**Comment by pbasilio** [comment]
I've been experimenting with the original sppsnantes and the difussion corrected nantes, but, i'm not getting 2 - 3 times more RT, the increments I'm getting are between 4% and 10% which I think i something that can be expected... Am I missing something to calculate with difussion?

**Comment by d-cooper** [comment]
Try making room with low absorption (0.1 or less) and very high diffusion
(close to 1). Then you should notice much higher differences.

sob., 26.12.2015 o 16:57 użytkownik pbasilio <notifications@github.com>
napisał:

**Comment by nicolas-f** [comment]
Thanks for the support @d-cooper . I'm closing the issue.
