### ISSUE TITLE
SPPS not stopping after "Cancel"

### ISSUE THREAD

**Issue by wbinek** [Ifsttar/I-Simpa#181]
The SPPS doesn't stop after pressing "Cancel" in progress window. To stop computation it has to be killed from task manager.

I've tested it with last AppVeyor build (1.0.105). It has been like that since quite some time but I thought it is just my fork.

**Comment by nicolas-f** [comment]
Yes. We must use a more recent version of wxWidgets to fix this issue, like this one:
https://github.com/wxWidgets/wxWidgets/tree/v3.0.3.1

This is because I provide a patch for being able to kill subprocess when using synchronized call to external program. https://github.com/wxWidgets/wxWidgets/pull/369

**Comment by wbinek** [comment]
Ok. Thank you for the answer.

**Comment by Picaut** [comment]
@nicolas-f this issue can be closed?

**Comment by nicolas-f** [comment]
The upgrade has not been done yet

**Comment by Picaut** [comment]
Done. Should be merge in version 1.3.4
