### ISSUE TITLE
Check sound source intersection

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/I-Simpa#37]
Check if a sound source is not in intersection with a wall.

If a sound source is in intersection, print an error with the sound source coordinate and name then cancel the spps computation.

**Comment by Picaut** [comment]
Note that, when a punctual receiver is closed to a face, the volume recevier can crossed the face. This may be a problem, since the sound level is normalized according to the volume receiver. In this last example, i.e. a part of the volume can not be crossed by particles (with SPPS). The sound level should be normalized only by the receiver volume inside the room.
